---
version: 2
jobs:
  build:
    steps:
      - checkout
      - run:
          name: Install Docker.
          command: apt-get -y update; apt-get -y install docker
      - run:
          name: Build the image. 
          command: docker build -t ledger .
      - run:
          name: Verify ledger.
          command: docker run ledger:latest ledger -v
...
