---
version: 2
jobs:
  build:
    docker:
      - image: python:alpine3.7
    steps:
      - checkout
      - run:
          command: apt-get -y update
          command: apt-get -y install docker
      - run:
          name: Build the image. 
          command: docker build -t ledger .
      - run:
          name: Verify ledger.
          command: docker run ledger ledger -v
...
